### ISSUE TITLE
Present corresponding keycloak configuration

### ISSUE THREAD

**Issue by 1kastner** [swan-cern/jupyterhub-extensions#25]
How do I need to setup my keycloak so that it works hand in hand with the keycloak OAuth authenticator?

**Comment by diocas** [comment]
Hy @1kastner , our keycloak deployment is done by a different team at CERN, so I don't know for sure what are the configurations they used. 
But if you have a running Keycloack instance, it should be a matter of registering the application in order to get the id and the secret. Then follow the instruction in the readme (this is a OIDC authenticator, which is a superset of oAuth and simplifies a bit the config).

**Comment by 1kastner** [comment]
Thank you very much. I struggled a bit but now I figured out that it was not the fault of keycloak but unrelated issues I could solve. Now I made it work with a very simple keycloak setup, so I agree with you that it seems simple. Thank you for the quick answer!

**Comment by diocas** [comment]
Are you trying to deploy SWAN or generic Jupyter?

**Comment by 1kastner** [comment]
I was working in Jupyter in general. The problem was that I was working with self-signed certificated for a setup that I wanted to check on my own laptop before deployment. The information can be found in the [Jupyter Discourse Forum](https://discourse.jupyter.org/t/setup-oauth2-locally-tornado-curl-httpclient-curlerror-http-599-server-certificate-verification-failed-cafile-none-crlfile-none/7584/5).

I did think about diving deeper into SWAN because it seems to ship many important components I have come across before. At the same time I couldn't figure out based on the readme at https://github.com/swan-cern/jupyterhub-extensions what exactly this project tries to solve. When is SWAN a suitable option? Or when is it inappropriate to use SWAN? What was the initial motivation of the project?

**Comment by diocas** [comment]
Sorry for taking long to reply..
SWAN is suitable for a scientific environment but can be used in other use cases. We provide many software packages without having to install them in the Docker images (http://lcginfo.cern.ch/) by using CVMFS, so this is easier to maintain. At the same time we have integration with a powerful storage backend (EOS) and a sync&share service (CERNBox atm, but we're working to connect to generic services like ownCloud and to provide full functionality in JupyterLab). So this allows you to deploy a proper Jupyter solution as a service. If you're a single user, running in your pc, then it's a bit overkill.

**Comment by 1kastner** [comment]
Thank you very much @diocas! I am not a single user, I was only checking something locally that would potentially be rolled out at a later stage. Your plans sound great, thank you very much for sharing the code publicly here!
