### ISSUE TITLE
Problems with get_roles_for_token

### ISSUE THREAD

**Issue by rmalik2018** [swan-cern/jupyterhub-extensions#35]
We trying to use this module for our keycloak/jupyter authentication. This module works well in a setup where roles are defined in the keycloak. However, we dynamically update user attributes with role names (List<String>). Then we use Client Mapper to pick multivalued User Attribute. Here we pass the roles to KeycloakAuthenticator.

As soon as we create new "Mapper" in Client, it overwrites all the resource_access and it removes existing system roles too. It takes out parameters which are used by other parts of jupyter such as resource_access.broker.token(its used for provider token access). I can see why it is doing it, because the newly created mapper has higher priority and it uses Token Claim Name resouce_access.{client_id}.roles. One solution could be to read the roles from an alternative Token Claim name such as roles_claim_key. 

Is it possible to provide an update to have a roles_claim_key as configurable parameter; the default can be resource_access.{client_id}.roles . However, if we should be allowed change to  for example custom.roles. This would be massively help us.

This functionality exists on 

https://github.com/jupyterhub/oauthenticator/blob/f830d4b790cd2fa6e5a2f5d6ae9b1ee844490944/oauthenticator/generic.py#L23

but its for groups not for roles.

I think the below function needs updating; where you can pass either token or custom like : roles_claim_key

https://github.com/swan-cern/jupyterhub-extensions/blob/c250978c7f2666c0caca7861d98c0747574f218f/KeyCloakAuthenticator/keycloakauthenticator/auth.py#L149

    def get_roles_for_token(self, token):
        decoded_token = self._decode_token(token)
        return set(
            decoded_token.\
               get('resource_access', {'app': ''}).\
               get(self.client_id, {'roles_list': ''}).\
               get('roles', 'no_roles')
        )

Thanks for your help.

**Comment by diocas** [comment]
Hi @rmalik2018 
Currently we don't have that much time to do it, maybe in a couple of weeks... Sorry. How urgent is this for you?
You also have the possibility to open a PR with the change and we will merge it.
Cheers

**Comment by rmalik2018** [comment]
Looks good me, if you would like we can test it.
